spring.application.name=tictactoe-reporting
server.port=8081

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=tictactoe-reporting
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/reporting}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:reporting}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:reporting_secret}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

tictactoe.kafka.topic=tictactoe.events
tictactoe.kafka.groupId=tictactoe-reporting

spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration